#!/bin/bash

#IN="eDP1"
#EXT="HDMI1"

#if (xrandr | grep "$EXT connected"); then
    #xrandr --output $IN --auto --primary --output $EXT --auto --right-of $IN
##else
    ##xrandr --output $EXT --off
#fi
#sh $HOME/.fehbg
