#!/bin/bash

export DISPLAY=:0.0

mode="--right-of"

echo $1 >> /tmp/toto
if [ "$1" == "--right-of" ] || [ "$1" == "--left-of" ] || [ "$1" == "--same-as" ] || [ "$1" == "--off" ]; then
    mode=$1;
fi

function connect(){
    echo "xrandr --output $1 --auto $mode $2"
xrandr --output $1 --auto $mode $2
}

function disconnect(){
xrandr --output $1 --off
}

#cur=eDP1
#for out in "HDMI1" "HDMI2" "DP1" "DP2"; do
cur=eDP-1
for out in "HDMI-1" "HDMI-2" "DP-1" "DP-2"; do
    if [ "$(xrandr | grep "$out connected")" != "" ] && [ "$mode" != "--off" ]; then
        connect $out $cur;
        cur=$out;
    else
        disconnect $out;
    fi
done;

sh .fehbg

xset r rate 300 15
setxkbmap -option ctrl:nocaps
setxkbmap -option compose:ralt

